extends: ["airbnb", "prettier"]
parserOptions:
  ecmaVersion: 2022
  sourceType: "module"
env:
  es6: true
  browser: true
rules:
  no-debugger: 1
  react/jsx-filename-extension: 0
  react/no-string-refs: 0
  no-plusplus: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
  lines-between-class-members: 2
  jsx-a11y/label-has-for: 0
  react/no-did-mount-set-state: 0
  react/forbid-prop-types: 0
  padding-line-between-statements: [
    error,
    {
      blankLine: always,
      prev: function,
      next: "*"
    },
    {
      blankLine: always,
      prev: "*",
      next: "function"
    },
    {
      blankLine: always,
      prev: "*",
      next: "function"
    }
  ]
