extends: airbnb
parserOptions:
  ecmaVersion: 6
env:
  es6: true
  browser: true
ecmaFeatures:
  modules: true
rules:
  no-debugger: 2
  no-plusplus: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
