extends: ["airbnb", "prettier"]
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 8
  sourceType: "module"
env:
  es6: true
  browser: true
rules:
  no-debugger: 2
  react/jsx-filename-extension: 0
  react/no-string-refs: 0
  no-plusplus: 0
  class-methods-use-this: 0
  no-underscore-dangle: 0
  lines-between-class-members: 2
  padding-line-between-statements: [
    error,
    {
      blankLine: always,
      prev: function,
      next: "*"
    },
    {
      blankLine: always,
      prev: "*",
      next: "function"
    },
    {
      blankLine: always,
      prev: "*",
      next: "function"
    }
  ]
